### ISSUE TITLE
Array only containing a blank string fails to parse

### ISSUE THREAD

**Issue by mohag** [chobie/php-plist#1]
Sample:
```
require "plist.php";
Plist::parse('{ test = (""); }');
```

```
PHP Fatal error:  Uncaught Exception: 2parse error: unexpected token `)` found. in plist.php:233
Stack trace:
#0 plist.php(145): Plist::parse('{ test = (""); ...', 12, 16)
#1 test.php(7): Plist::parse('{ test = (""); ...')
#2 {main}
```
Adding a space after the last double quote gives better results... (No exceptions at least)

**Comment by mohag** [comment]
Replacing the relevant block with this seem to fix it for me:
```
                                                } else if ($DQ == true && ($current == '"' && $previous != "\\")) {
                                                        $value = substr($data,$mark,$offset-$mark);
                                                        $result[] = $value;
                                                        $mark =  0;
                                                        $sub = 0x00;
                                                } else if ($current == ")"){
```

(Set $sub to 0 instead of 2 after end of string...) (It might break other things, but it makes my file parse...)

**Comment by mohag** [comment]
0x01 seems potentially more correct...

**Comment by mohag** [comment]
It fixes the crash, but array ends up containing the string '"' as first item and the preceding items as the second item with 0x01 in there...

0x00 works correctly on my file.
